server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

application:
  name: Tooltips4Vaadin Demo

# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
